#pragma once
# define SHOW_TRIANGLES false
# define ENABLE_WORLD_GENERATION true
# define SHOW_DEBUG true
# define SHOW_LOADCHUNK_TIME true

# define W_WIDTH 800
# define W_HEIGHT 600
# define RENDER_DISTANCE 10
# define NB_CHUNKS RENDER_DISTANCE * RENDER_DISTANCE
# define Y_RENDER_DISTANCE 1
# define XZ_RENDER_DISTANCE 10